#!/bin/bash
echo "Cloning Private Repo..."
git clone https://$PRIVATE_REPO_TOKEN@github.com/Uf-prince/BILAL-MD1 private

cd private || { echo "Clone failed!"; exit 1; }

echo "Creating config.env with user values..."
cat > config.env <<EOL
SESSION_ID=${SESSION_ID}
OWNER_NUMBER=${OWNER_NUMBER}
OWNER_NAME=${OWNER_NAME}
BOT_NAME=${BOT_NAME}
PREFIX=${PREFIX:-.}
AUTO_STATUS_SEEN=${AUTO_STATUS_SEEN}
AUTO_STATUS_REPLY=${AUTO_STATUS_REPLY}
AUTO_STATUS_REACT=${AUTO_STATUS_REACT}
AUTO_STATUS_MSG=${AUTO_STATUS_MSG}
WELCOME=${WELCOME}
ADMIN_EVENTS=${ADMIN_EVENTS}
ANTI_LINK=${ANTI_LINK}
MENTION_REPLY=${MENTION_REPLY}
MENU_IMAGE_URL=${MENU_IMAGE_URL}
STICKER_NAME=${STICKER_NAME}
CUSTOM_REACT=${CUSTOM_REACT}
CUSTOM_REACT_EMOJIS=${CUSTOM_REACT_EMOJIS}
DELETE_LINKS=${DELETE_LINKS}
DESCRIPTION=${DESCRIPTION}
ALIVE_IMG=${ALIVE_IMG}
LIVE_MSG=${LIVE_MSG}
READ_MESSAGE=${READ_MESSAGE}
AUTO_REACT=${AUTO_REACT}
ANTI_BAD=${ANTI_BAD}
MODE=${MODE}
ANTI_LINK_KICK=${ANTI_LINK_KICK}
AUTO_VOICE=${AUTO_VOICE}
AUTO_STICKER=${AUTO_STICKER}
AUTO_REPLY=${AUTO_REPLY}
ALWAYS_ONLINE=${ALWAYS_ONLINE}
PUBLIC_MODE=${PUBLIC_MODE}
AUTO_TYPING=${AUTO_TYPING}
READ_CMD=${READ_CMD}
DEV=${DEV}
ANTI_VV=${ANTI_VV}
ANTI_DEL_PATH=${ANTI_DEL_PATH}
AUTO_RECORDING=${AUTO_RECORDING}
EOL

echo "Installing dependencies..."
npm install

echo "Starting bot..."
node index.js
